#!/usr/bin/python
from socket import socket
from sys import argv
import struct
import settings


def send_msg(sock, msg):
  msg = struct.pack('>I', len(msg)) + msg
  sock.sendall(msg)

def recv_msg(sock):
  raw_msglen = recvall(sock, 4)
  if not raw_msglen:
    return None
  msglen = struct.unpack('>I', raw_msglen)[0]
  return recvall(sock, msglen)

def recvall(sock, n):
  data = ''
  while len(data) < n:
    packet = sock.recv(n - len(data))
    if not packet:
      return None
    data += packet
  return data


if __name__ == '__main__':
  if len(argv) > 1:
    s = socket()
    try:
      s.connect(settings.local_conn)
    except KeyboardInterrupt:
      exit(1)
    except Exception:
      print('ProxyMiner not online')
      exit(1)
    send_msg(s, ' '.join(argv))
    print(recv_msg(s))